#ifndef COORDS_H
#define COORDS_H

#include "typedefs.h"

/**
 * Cube-coordinate model of Gliński's hexagonal board.
 *
 * Every cell has coordinates (q, r, s) with q + r + s == 0, lying inside the
 * hexagon max(|q|, |r|, |s|) <= 5. That yields exactly 91 cells. The board and
 * all lookup tables are generated by initCoords() rather than hand-written, so
 * the cell set is correct by construction.
 *
 * Algebraic names follow Gliński: files a..l (the letter 'j' is skipped, so the
 * 11 files are a b c d e f g h i k l) and per-file ranks numbered from 1 upward.
 */

extern Cell CELLS[NUM_SQUARES];        // index 0..90 -> cell
extern int CUBE_TO_INDEX[11][11][11];  // [q+5][r+5][s+5] -> index, or -1

void initCoords(void);

// Returns the linear index for a cube coord, or -1 if off-board / invalid.
int cubeToIndex(int q, int r, int s);

// Returns index for an algebraic name like "f6", or -1 if unknown.
int nameToIndex(const char *name);

// Returns the algebraic name for an index, or "??" if out of range.
const char *indexToName(int index);

static inline bool isValidIndex(int index) {
    return index >= 0 && index < NUM_SQUARES;
}

// Movement direction tables in cube space.
extern const int ROOK_DIRS[6][3];    // 6 orthogonal (edge) directions
extern const int BISHOP_DIRS[6][3];  // 6 diagonal (vertex) directions
extern const int KING_DIRS[12][3];   // rook + bishop, one step
extern const int KNIGHT_DIRS[12][3]; // 12 hex knight leaps

#endif
